version: '3.8'

services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm_1
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      TZ: 'Asia/Seoul'
      # These are read from the .env file in the same directory
      INITIAL_ADMIN_EMAIL: ${NPM_ADMIN_EMAIL}
      INITIAL_ADMIN_PASSWORD: ${NPM_ADMIN_PASSWORD}
    volumes:
      - ./npm_data/data:/data
      - ./npm_data/letsencrypt:/etc/letsencrypt
    networks:
      - common

  redis:
    image: redis:latest
    container_name: redis_1
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      TZ: 'Asia/Seoul'
    # This is read from the .env file
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis_data:/data
    networks:
      - common

  elasticsearch:
    build:
      context: ./elasticsearch
    container_name: elasticsearch_1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ELASTIC_PASSWORD=${REDIS_PASSWORD}
      - TZ=Asia/Seoul
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data  # 데이터 영구 저장
      - ./elasticsearch/volumes/plugins:/usr/share/elasticsearch/plugins  # Nori 플러그인 저장
    networks:
      - common

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.3
    container_name: kibana_1
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_1:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${REDIS_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - common

networks:
  common:
    driver: bridge
    name: common
