spring:
  autoconfigure:
    exclude:
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME} # RDS PostgreSQL
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  analytics:
    google:
      analytics:
        credentials-path: classpath:ga4-service-account.json

logging:
  level:
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
    com.back: INFO
custom:
  site:
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"
    name: mori-mori